@extends('admin.layout')
@section('title',$campaign->exists ? 'Edit campaign' : 'Create campaign')
@section('description', 'Create a clear message, choose its audience and control when it appears.')
@section('page-actions')<a class="button secondary" href="{{ route('admin.campaigns') }}">All campaigns</a>@endsection
@section('content')
<form method="post" action="{{ $campaign->exists ? route('admin.campaign.save',$campaign) : route('admin.campaign.create') }}" id="campaign-form">@csrf
<div class="panel"><h2>Message</h2><div class="fields">
<label>Internal name<input name="name" required maxlength="120" value="{{ old('name',$campaign->name) }}"></label>
<label>Message type<select name="type">@foreach(['popup'=>'Popup','banner'=>'Banner','push'=>'Push notification'] as $value=>$label)<option value="{{ $value }}" @selected(old('type',$campaign->type)===$value)>{{ $label }}</option>@endforeach</select></label>
<label>Title<input name="title" maxlength="150" required value="{{ old('title',$campaign->title) }}"></label>
<label>Status<select name="status">@foreach(['draft','active','paused','completed','cancelled'] as $state)<option @selected(old('status',$campaign->status ?? 'draft')===$state)>{{ $state }}</option>@endforeach</select></label>
<label class="full">Message<textarea name="body" maxlength="3000" required>{{ old('body',$campaign->body) }}</textarea></label>
<label>Image URL <small>(optional, HTTPS)</small><input type="url" name="image_url" value="{{ old('image_url',$campaign->image_url) }}"></label>
<label>Button destination <small>(optional)</small><input type="url" name="action_url" value="{{ old('action_url',$campaign->action_url) }}"></label>
<label>Button text<input name="button_text" maxlength="40" required value="{{ old('button_text',$campaign->button_text ?? 'Open') }}"></label>
<label>Priority <small>(higher appears first)</small><input type="number" name="priority" min="0" max="1000" required value="{{ old('priority',$campaign->priority ?? 0) }}"></label>
</div></div>
<div class="panel"><h2>Delivery scope</h2><label>Send to<select name="delivery_scope"><option value="test" @selected(($campaign->delivery_scope ?? 'test')==='test')>Selected test devices</option><option value="all" @selected($campaign->delivery_scope==='all')>Everyone matching the audience</option></select></label>@foreach($testDevices as $device)<label><input type="checkbox" name="test_installation_ids[]" value="{{ $device->id }}" @checked(in_array($device->id,$campaign->test_installation_ids ?? []))> {{ $device->label ?: $device->id }}</label>@endforeach</div><div class="panel"><div class="form-section-title"><x-admin.icon name="users" /><h2>Audience</h2></div><div class="fields"><label>Match<select id="audience-mode"><option value="all">All conditions</option><option value="any">Any condition</option></select></label><label>Audience percentage<input id="audience-percentage" type="number" min="0" max="100" value="100"></label></div><div id="rules" style="margin:18px 0"></div><button type="button" class="secondary" id="add-rule">Add condition</button><details><summary>Audience JSON and exclusions</summary><textarea class="code" name="audience" id="audience-json">{{ old('audience',json_encode($campaign->audience ?? ['mode'=>'all','percentage'=>100,'rules'=>[]],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)) }}</textarea><small>Use test_device equals true for a test send. Exclusions: exclude_installation_ids.</small></details></div>
<div class="panel"><div class="form-section-title"><x-admin.icon name="clock" /><h2>Timing</h2></div><div class="fields">
<label>Trigger<select name="trigger">@foreach(['app_open'=>'Only while opening the app','first_open'=>'Only first opening after installation','updated'=>'Only first opening after an update','foreground'=>'Return to app','interval'=>'Periodic check','any'=>'Any eligible check','schedule'=>'Scheduled push'] as $value=>$label)<option value="{{ $value }}" @selected(old('trigger',$campaign->trigger ?? 'app_open')===$value)>{{ $label }}</option>@endforeach</select></label>
<label>Timezone<input name="timezone" required value="{{ old('timezone',$campaign->timezone ?? 'Africa/Addis_Ababa') }}"></label>
<label>Start <small>(blank = now)</small><input type="datetime-local" name="starts_at" value="{{ old('starts_at',$campaign->starts_at?->timezone($campaign->timezone)->format('Y-m-d\TH:i')) }}"></label>
<label>End <small>(optional)</small><input type="datetime-local" name="ends_at" value="{{ old('ends_at',$campaign->ends_at?->timezone($campaign->timezone)->format('Y-m-d\TH:i')) }}"></label>
<label>Repeat push every N minutes <small>(blank = once)</small><input type="number" name="repeat_minutes" min="15" value="{{ old('repeat_minutes',$campaign->repeat_minutes) }}"><small>1440 = daily; 10080 = weekly, anchored to start time.</small></label>
<label>Delay after app opens <small>(seconds)</small><input type="number" name="delay_seconds" min="0" max="3600" required value="{{ old('delay_seconds',$campaign->delay_seconds ?? 0) }}"><small>Opening-only messages need a delay shorter than the opening window in Configuration. Late messages are skipped.</small></label>
<label>Quiet hours start<input type="time" name="quiet_start" value="{{ old('quiet_start',$campaign->quiet_start) }}"></label><label>Quiet hours end<input type="time" name="quiet_end" value="{{ old('quiet_end',$campaign->quiet_end) }}"></label>
</div></div>
<div class="panel"><div class="form-section-title"><x-admin.icon name="shield" /><h2>Frequency and dismissal</h2></div><div class="fields">
@foreach(['max_per_installation'=>['Lifetime maximum (0 = unlimited)',1],'max_per_day'=>['Maximum per day',1],'cooldown_minutes'=>['Minimum minutes between appearances',1440]] as $field=>[$label,$default])<label>{{ $label }}<input type="number" name="{{ $field }}" min="{{ $field==='max_per_day' ? 1 : 0 }}" required value="{{ old($field,$campaign->{$field} ?? $default) }}"></label>@endforeach
<label>Once per session<select name="once_per_session"><option value="1" @selected(old('once_per_session',$campaign->once_per_session ?? true))>Yes</option><option value="0" @selected(!old('once_per_session',$campaign->once_per_session ?? true))>No</option></select></label>
<label>Allow “Do not show again”<select name="allow_opt_out"><option value="1" @selected(old('allow_opt_out',$campaign->allow_opt_out ?? true))>Yes</option><option value="0" @selected(!old('allow_opt_out',$campaign->allow_opt_out ?? true))>No</option></select></label><input type="hidden" name="dismissible" value="1">
</div><details><summary>Language versions</summary><textarea class="code" name="translations">{{ old('translations',json_encode($campaign->translations ?? new stdClass,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)) }}</textarea><small>Example: {"am":{"title":"…","body":"…","button_text":"…"}}. Unmatched languages use the main message.</small></details></div>
<div class="form-footer"><p>Save your changes, then preview on a test device.</p><div class="actions">@if(in_array(auth()->user()->role,['owner','operator']))<button>Save campaign</button>@endif<a class="button secondary" href="{{ route('admin.campaigns') }}">Back</a></div></div>
</form>
<script>
(()=>{const source=document.getElementById('audience-json'),rules=document.getElementById('rules'),mode=document.getElementById('audience-mode'),percent=document.getElementById('audience-percentage');let audience;try{audience=JSON.parse(source.value)}catch{audience={mode:'all',percentage:100,rules:[]}}
const fields=['manufacturer','model','webview_version','push_available','low_ram','version_code','android_version','language','notifications_enabled','promotions_enabled','session_count','sessions_7d','test_device','installation_id','age_days','inactive_days','displayed_campaign','clicked_campaign'];
function sync(){audience.mode=mode.value;audience.percentage=Number(percent.value);audience.rules=[...rules.children].map(row=>{let value=row.querySelector('input').value;try{value=JSON.parse(value)}catch{}return{field:row.children[0].value,op:row.children[1].value,value}});source.value=JSON.stringify(audience,null,2)}
function add(rule={field:'language',op:'eq',value:'en'}){const row=document.createElement('div');row.className='rule';for(const [values,selected] of [[fields,rule.field],[['eq','ne','gte','lte','in','not_in'],rule.op]]){const select=document.createElement('select');select.setAttribute('aria-label',row.children.length?'Comparison':'Audience field');for(const value of values){const option=document.createElement('option');option.value=value;option.textContent=value.replaceAll('_',' ');select.append(option)}select.value=selected;select.onchange=sync;row.append(select)}const input=document.createElement('input');input.setAttribute('aria-label','Comparison value');input.value=typeof rule.value==='string'?rule.value:JSON.stringify(rule.value);input.oninput=sync;row.append(input);const remove=document.createElement('button');remove.type='button';remove.className='secondary';remove.textContent='Remove';remove.onclick=()=>{row.remove();sync()};row.append(remove);rules.append(row)}
function render(){rules.replaceChildren();mode.value=audience.mode||'all';percent.value=audience.percentage??100;(audience.rules||[]).forEach(add)}render();mode.onchange=sync;percent.oninput=sync;document.getElementById('add-rule').onclick=()=>{add();sync()};source.addEventListener('change',()=>{try{audience=JSON.parse(source.value);render()}catch{}});
})();
</script>
@endsection
