@extends('admin.layout')
@section('title', 'Campaign preview')
@section('description', 'Review your message, then check the native layout on a test phone.')
@section('page-actions')<a class="button secondary" href="{{ route('admin.campaign.edit', $campaign) }}"><x-admin.icon name="settings" size="16" />Edit campaign</a>@endsection
@section('content')
<div class="grid">
<section class="panel"><div class="panel-heading"><div><h2>Message preview</h2><p>{{ $campaign->name }}</p></div><span class="badge badge-neutral">{{ ucfirst($campaign->type) }}</span></div><form method="get"><label>Preview language<select name="language"><option value="default">Default language</option>@foreach(array_keys($campaign->translations ?? []) as $code)<option value="{{ $code }}" @selected($language === $code)>{{ $code }}</option>@endforeach</select></label><button class="secondary" style="margin-top:10px">Update preview</button></form><div class="campaign-device"><div class="preview-topbar"><span class="preview-brand"><img src="{{ asset('betna-logo.png') }}" alt="">Betna</span><x-admin.icon name="menu" size="16" /></div><div class="preview-screen"><div class="preview-popup">@if($campaign->image_url)<img src="{{ $campaign->image_url }}" alt="Campaign image" referrerpolicy="no-referrer">@endif<div class="preview-pill">{{ ucfirst($campaign->type) }} from Betna</div><h2>{{ $localized['title'] ?? $campaign->title }}</h2><p style="white-space:pre-wrap">{{ $localized['body'] ?? $campaign->body }}</p><div class="button-row"><button type="button">{{ $localized['button_text'] ?? $campaign->button_text }}</button><button type="button" class="secondary">Close</button></div></div></div></div><p class="preview-note">This is a content preview. Your test phone shows the actual Android layout.</p><details><summary>Delivery details</summary><p>Trigger: <span class="badge badge-neutral">{{ str_replace('_', ' ', $campaign->trigger) }}</span></p><p>Action URL: <code>{{ $campaign->action_url ?: 'None' }}</code></p></details></section>
<section class="panel"><div class="panel-heading"><div><h2>Test before publishing</h2><p>Deliver to selected staff phones only</p></div><x-admin.icon name="shield" class="muted" /></div>@if(in_array(auth()->user()->role, ['owner', 'operator']))<form method="post" action="{{ route('admin.campaign.test', $campaign) }}">@csrf<div class="test-device-list">@forelse($testDevices as $device)<label class="test-device-option"><input type="checkbox" name="installation_ids[]" value="{{ $device->id }}"><span>{{ $device->label ?: $device->model ?: $device->id }}<small>{{ $device->language }} · {{ $device->version_name }}</small></span><x-admin.icon name="devices" size="18" /></label>@empty<div class="large-empty"><div class="empty-icon"><x-admin.icon name="devices" size="26" /></div><h2>Add your first test phone</h2><p>Open Devices and mark a staff installation as a test device.</p><a class="button secondary" href="{{ route('admin.installations') }}">Manage devices</a></div>@endforelse</div><p class="table-caption">A draft can be tested without activating it. Test deliveries appear separately in reports.</p><button @disabled($testDevices->isEmpty())><x-admin.icon name="campaign" size="16" />Send test message</button></form>@else<p class="muted">An owner or operator can send a test message.</p>@endif</section>
</div>
@endsection
