@extends('admin.layout')
@section('title','Connection & tabs')
@section('content')
<div class="panel"><p>External public domains are allowed. DNS rules choose resolvers; they do not approve websites. Changes never reload an active website page.</p>
<form method="post" action="{{ route('admin.configuration.save') }}" id="config-form">@csrf
<div class="fields"><label>Main website<input id="website" type="url" required value="{{ $configuration['website_url'] }}"></label><label>Publish to<select name="scope" id="scope"><option value="test">Selected test devices</option><option value="all">Everyone</option></select></label></div>
<fieldset><legend>Test devices</legend>@forelse($testDevices as $device)<label><input type="checkbox" name="installation_ids[]" value="{{ $device->id }}"> {{ $device->label ?: $device->id }} · {{ $device->version_name }}</label>@empty<p>Mark your phone as a test device in Installations first.</p>@endforelse</fieldset>
<h2>DNS providers</h2><div class="fields"><label>Encrypted DNS<select id="dns-enabled"><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label>Use phone DNS if every provider fails<select id="dns-fallback"><option value="false">No</option><option value="true">Yes</option></select><small>Phone DNS may reproduce the original block.</small></label></div>
<div id="dns-providers"></div><button type="button" class="secondary" id="add-provider">Add DNS provider</button><h3>Domain routing rules</h3><p>Optional: choose the first resolver to try for a domain and its subdomains.</p><div id="dns-rules"></div><button type="button" class="secondary" id="add-rule">Add domain rule</button>
<h2>Tabs & session preservation</h2><div class="fields"><label>Close external tabs automatically<select id="auto-close"><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label>Close after minutes<input id="timeout" type="number" min="1" max="10080" value="{{ $configuration['tabs']['timeout_minutes'] }}"></label><label>Measure time from<select id="basis"><option value="opened">Tab opening</option><option value="activity">Last activity</option></select></label><label>Maximum tabs including main<input id="max-tabs" type="number" min="2" max="20" value="{{ $configuration['tabs']['max_tabs'] }}"></label><label>Session preservation<select id="preserve"><option value="true">Preserve tabs on restart</option><option value="false">New homepage on restart</option></select><small>Login cookies are retained in both modes. Expired external tabs still close.</small></label></div>
<h2>Maintenance notice</h2><div class="fields"><label>Notice<select id="maintenance-enabled"><option value="false">Disabled</option><option value="true">Enabled</option></select></label><label>Behaviour<select id="maintenance-blocking"><option value="false">Notice with Continue button</option><option value="true">Block browsing until disabled</option></select></label><label>Title<input id="maintenance-title" maxlength="120"></label></div><label>Message<textarea id="maintenance-message" maxlength="2000" rows="3"></textarea></label>
<h2>Other settings</h2><div class="fields"><label>Backup homepages, one per line<textarea id="backups" rows="3"></textarea></label><label>Opening popup window in seconds<input id="opening-window" type="number" min="2" max="30"></label><label>Promotional messages per day<input id="daily-cap" type="number" min="1" max="100"></label></div><p>Telegram support is managed in <a href="{{ route('admin.launch') }}">Support & downloads</a>.</p>
<details><summary>Advanced configuration</summary><textarea name="payload" id="configuration-json" class="code" rows="18">{{ old('payload',json_encode($configuration,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)) }}</textarea><p>Use “Load advanced values” after editing this text.</p><button type="button" class="secondary" id="load-advanced">Load advanced values</button></details>
@if(auth()->user()->role==='owner')<button>Publish configuration</button>@endif</form></div>
<div class="panel"><h2>Configuration history</h2><table><tr><th>Revision</th><th>Audience</th><th>Created UTC</th><th>Actions</th></tr>@foreach($history as $entry)<tr><td>#{{ $entry->id }}</td><td>{{ $entry->scope==='test' ? 'Test devices: '.count($entry->installation_ids ?? []) : 'Everyone' }}</td><td>{{ $entry->created_at->format('Y-m-d H:i') }}</td><td>@if(auth()->user()->role==='owner')<form method="post" action="{{ route('admin.configuration.rollback',$entry) }}">@csrf<button class="secondary">Restore to same audience</button></form>@if($entry->scope==='test')<form method="post" action="{{ route('admin.configuration.promote',$entry) }}">@csrf<button>Publish this revision to everyone</button></form>@endif @endif</td></tr>@endforeach</table></div>
<script src="{{ asset('configuration.js') }}" defer></script>
@endsection
