@extends('admin.layout')
@section('title','Device report')
@section('content')
@if($device->deviceIdentity)
<div class="panel"><div class="panel-heading"><div><h2>Recognized device</h2><p>{{ number_format($device->deviceIdentity->installations_count) }} installation records linked to this Android device profile</p></div><a class="button secondary" href="{{ route('admin.device.identity', $device->deviceIdentity) }}"><x-admin.icon name="clock" size="16" />Installation history</a></div></div>
@else
<div class="notice">Device identity has not been reported for this installation. Updating to Betna 0.5.0 can link future installation records.</div>
@endif
<div class="panel"><div class="eyebrow">{{ $device->id }}</div><h2>{{ $device->label ?: $device->manufacturer.' '.$device->model }}</h2><div class="stats"><div class="stat"><span>App version</span><strong>{{ $device->version_name }}</strong></div><div class="stat"><span>App openings</span><strong>{{ $device->session_count }}</strong></div><div class="stat"><span>VPN</span><strong style="font-size:20px">{{ $device->vpn_status }}</strong></div><div class="stat"><span>Location permission</span><strong style="font-size:20px">{{ $device->location_permission }}</strong></div></div><p>Android API {{ $device->android_version }} · WebView {{ $device->webview_version ?: 'Unknown' }} · Last seen {{ $device->last_seen_at?->diffForHumans() ?: 'Never' }}</p><p class="muted">One installation may be used by several players. Website login success is not available without provider integration. Login attempts never contain usernames or passwords.</p></div>
<div class="panel table-wrap"><h2>Location history</h2><table><tr><th>Observed UTC</th><th>Coordinates</th><th>Precision / accuracy</th></tr>@forelse($locations as $p)<tr><td>{{ $p->observed_at }}</td><td>{{ $p->latitude }}, {{ $p->longitude }}</td><td>{{ $p->precision }} · {{ number_format($p->accuracy_m) }} m</td></tr>@empty<tr><td colspan="3">No permitted location samples.</td></tr>@endforelse</table></div>
<div class="panel table-wrap"><h2>App activity and login-attempt history</h2><table><tr><th>Occurred UTC</th><th>Event</th><th>Website host</th><th>Reference</th><th>Version</th></tr>@forelse($events as $e)<tr><td>{{ $e->occurred_at }}</td><td>{{ $e->type }}</td><td>{{ $e->host }}</td><td>{{ $e->code }}</td><td>{{ $e->version_code }}</td></tr>@empty<tr><td colspan="5">No activity received.</td></tr>@endforelse</table>{{ $events->links() }}</div>
<div class="panel"><h2>Cache commands</h2>@forelse($commands as $c)<p>{{ $c->created_at }} · {{ $c->timing }} · <span class="chip">{{ $c->status }}</span> {{ $c->failure_code }}</p>@empty<p>No commands.</p>@endforelse</div>
@endsection
