@extends('admin.layout')
@section('title', 'Devices')
@section('description', 'Understand each installation, explore activity and manage your test phones.')
@section('content')
<div class="panel filter-panel"><div class="filter-heading"><x-admin.icon name="search" size="16" />Find an installation <span class="badge badge-neutral" style="margin-left:auto">{{ number_format($devices->total()) }} matching</span></div><form class="filter" method="get"><label>Search<input name="q" value="{{ request('q') }}" placeholder="Label, phone model or ID" maxlength="120"></label><label>Version code<input type="number" name="version" value="{{ request('version') }}" min="1" placeholder="All versions"></label><label>Device group<select name="test"><option value="">All devices</option><option value="1" @selected(request('test') === '1')>Test devices</option><option value="0" @selected(request('test') === '0')>Regular devices</option></select></label><label style="padding:10px 0"><input type="checkbox" name="online" value="1" @checked(request('online'))> Online now</label><button>Apply filters</button>@if(request()->query())<a class="button secondary" href="{{ route('admin.installations') }}">Reset</a>@endif</form><p class="table-caption">An installation may be used by more than one person. Mark staff phones as test devices before testing campaigns.</p></div>
<div class="panel"><div class="panel-heading"><div><h2>Your installations</h2><p>Most recently active first</p></div><span class="badge badge-neutral">{{ $devices->firstItem() ?? 0 }}–{{ $devices->lastItem() ?? 0 }} of {{ number_format($devices->total()) }}</span></div><div class="table-wrap"><table class="device-table"><thead><tr><th>Installation</th><th>App & device</th><th>Activity</th><th>Preferences</th><th>Test device</th></tr></thead><tbody>@forelse($devices as $device)
<tr><td data-label="Installation"><div class="row-label"><span class="device-avatar"><x-admin.icon name="devices" size="18" /></span><div>@if(in_array(auth()->user()->role, ['owner', 'operator']))<a class="row-title" href="{{ route('admin.device', $device) }}">{{ $device->label ?: ($device->model ?: 'Android device') }}</a>@else<strong class="row-title">{{ $device->label ?: ($device->model ?: 'Android device') }}</strong>@endif<div class="row-meta"><code title="{{ $device->id }}">{{ \Illuminate\Support\Str::limit($device->id, 18) }}</code></div></div></div>@if($device->revoked_at)<span class="badge badge-warning" style="margin-top:9px">Management access revoked</span>@endif</td>
<td data-label="App & device"><strong>v{{ $device->version_name }}</strong> <span class="badge badge-neutral">API {{ $device->android_version }}</span><div class="row-meta">{{ $device->manufacturer }} {{ $device->model }} · {{ $device->language }}</div><details><summary>Compatibility details</summary><small>Version code {{ $device->version_code }}<br>WebView {{ $device->webview_version ?: 'Unknown' }}<br>{{ $device->low_ram ? 'Low memory' : 'Standard memory' }}<br>Push: {{ $device->push_available ? 'available' : 'unavailable' }}<br>Reported risk: {{ ($device->capabilities['root_signal'] ?? false) ? 'root signal' : 'none reported' }} {{ ($device->capabilities['debugger_attached'] ?? false) ? 'debugger attached' : '' }}</small></details></td>
<td data-label="Activity">@if($device->foreground && $device->last_seen_at?->gte(now()->subSeconds(config('mobile.online_seconds'))))<span class="badge badge-success"><span class="status-dot"></span>Online</span>@else<span class="badge badge-neutral">Inactive</span>@endif<div class="row-meta">{{ $device->last_seen_at?->diffForHumans() ?? 'Not yet active' }}</div></td>
<td data-label="Preferences"><span class="badge {{ $device->notifications_enabled ? 'badge-success' : 'badge-neutral' }}">Notifications {{ $device->notifications_enabled ? 'on' : 'off' }}</span><div class="row-meta">Promotions {{ $device->promotions_enabled ? 'on' : 'off' }}</div></td>
<td data-label="Test device">@if(in_array(auth()->user()->role, ['owner', 'operator']))<details><summary><span class="badge {{ $device->test_device ? 'badge-warning' : 'badge-neutral' }}">{{ $device->test_device ? 'Test device' : 'Regular device' }}</span> Edit</summary><form method="post" action="{{ route('admin.installation.save', $device) }}">@csrf<label>Device label<input name="label" value="{{ $device->label }}" placeholder="Staff phone" maxlength="80"></label><label style="margin-top:8px">Group<select name="test_device"><option value="0">Regular device</option><option value="1" @selected($device->test_device)>Test device</option></select></label><button class="secondary" style="margin-top:10px">Save device</button></form></details>@else<span class="badge badge-neutral">{{ $device->test_device ? 'Test device' : 'Regular device' }}</span>@endif</td></tr>
@empty<tr><td colspan="5" class="empty">No matching installations. Try another search, or connect a Betna app.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $devices->links() }}</div></div>
@if(auth()->user()->role === 'owner')<details class="panel"><summary>Installation access controls</summary><p class="muted">Revoke management access only for suspected abuse. The installation will lose remote settings and campaigns.</p>@foreach($devices as $device)<form method="post" action="{{ route('admin.installation.revoke', $device) }}" class="actions">@csrf<span>{{ $device->label ?: $device->id }}</span><button class="secondary" @disabled($device->revoked_at)>Revoke access</button></form>@endforeach</details>@endif
@endsection
