<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','Overview') · Betna</title><link rel="stylesheet" href="{{ asset('admin.css') }}"></head>
<body><div class="shell"><aside><a class="brand" href="{{ route('admin.dashboard') }}"><span class="brand-icon">A</span> Betna</a><div class="caption">ANDROID MANAGEMENT</div><nav>
@foreach(['dashboard'=>'Overview','installations'=>'Installations','campaigns'=>'Campaigns','configuration'=>'Connection & tabs','releases'=>'App releases','audit'=>'Activity log','launch'=>'Support & downloads','connections'=>'Connection reports'] as $key=>$label)<a class="{{ request()->routeIs('admin.'.$key.'*') ? 'active' : '' }}" href="{{ route('admin.'.$key) }}">{{ $label }}</a>@endforeach
@if(auth()->user()->role === 'owner')<a href="{{ route('admin.staff') }}">Staff access</a>@endif
<a href="{{ route('two-factor.recovery') }}">Account security</a></nav><div class="account"><strong>{{ auth()->user()->name }}</strong><span>{{ ucfirst(auth()->user()->role) }}</span><form method="post" action="{{ route('logout') }}">@csrf<button class="text-button">Sign out</button></form></div></aside>
<main><header><div><div class="eyebrow">CONTROL CENTER</div><h1>@yield('title','Overview')</h1></div><span class="chip">Android · Direct APK</span></header>
@if(session('status'))<div class="notice" role="status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="errors" role="alert"><strong>Check these fields</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@yield('content')<footer>Installation-based analytics · Online means foreground activity in the last 90 seconds · Campaign times use the selected timezone</footer></main></div></body></html>
