@extends('admin.layout')
@section('title','Betna VPN')
@section('content')
<div class="stats"><div class="stat"><span>Recently connected</span><strong>{{ $connected }}</strong></div><div class="stat"><span>Reported download this month</span><strong>{{ number_format($rx/1073741824,2) }} GiB</strong></div><div class="stat"><span>Reported upload this month</span><strong>{{ number_format($tx/1073741824,2) }} GiB</strong></div></div>
@if($budgetAlert)<div class="errors">VPN usage estimate has reached 80% of your budget. Check your hosting-provider bill and capacity.</div>@endif<div class="panel"><p>Estimated infrastructure cost this month: <strong>${{ number_format($estimatedCost,2) }}</strong>. Based on configured rates and device-reported traffic; not a provider invoice.</p></div><div class="panel"><h2>Administrator connection policy</h2><p>Android permission is requested on first opening. ON requires a verified VPN tunnel; no direct website fallback. Users can revoke permission in Android settings. Device traffic counters are diagnostic snapshots, not billing totals.</p><form method="post" action="{{ route('admin.vpn.save') }}">@csrf<div class="fields"><label>VPN mode<select name="enabled"><option value="0">OFF — normal connection and DNS</option><option value="1" @selected($configuration['vpn']['enabled'])>ON — VPN required</option></select></label><label>Apply changes<select name="apply"><option value="next_open">Next opening — preserve current session</option><option value="immediate" @selected($configuration['vpn']['apply']==='immediate')>Immediately — may interrupt a game</option></select></label></div><div class="fields"><label>Publish to<select name="scope"><option value="test">Selected test devices</option><option value="all">Everyone</option></select></label><label>Test installation IDs<select name="installation_ids[]" multiple>@foreach(\App\Models\Installation::where('test_device',true)->get() as $device)<option value="{{ $device->id }}">{{ $device->label ?: $device->id }}</option>@endforeach</select></label></div><h3 style="margin-top:22px">Primary and backup WireGuard servers</h3>@for($n=0;$n<max(1,count($configuration['vpn']['servers']));$n++)<div class="fields"><label>Server name<input name="servers[{{ $n }}][name]" value="{{ $configuration['vpn']['servers'][$n]['name'] ?? 'Primary' }}"></label><label>Endpoint host:port<input name="servers[{{ $n }}][endpoint]" value="{{ $configuration['vpn']['servers'][$n]['endpoint'] ?? '' }}" placeholder="vpn.example.com:51820"></label><label class="full">Server public key<input name="servers[{{ $n }}][public_key]" value="{{ $configuration['vpn']['servers'][$n]['public_key'] ?? '' }}" placeholder="Base64 WireGuard public key"></label></div>@endfor<h3 style="margin-top:22px">Budget estimates and alerts</h3><div class="fields">@foreach(['included_gib'=>'Included monthly GiB','base_cost_usd'=>'Base server cost USD','excess_usd_per_gib'=>'Extra USD per GiB','budget_usd'=>'Monthly budget USD'] as $key=>$label)<label>{{ $label }}<input type="number" step="0.01" min="0" name="{{ $key }}" value="{{ $configuration['vpn'][$key] ?? \App\Services\ConfigurationService::defaults()['vpn'][$key] }}"></label>@endforeach</div><div id="vpn-extra"></div><button type="button" class="secondary" onclick="addVpnServer()">Add backup server</button><button>Publish VPN policy</button></form></div>
<div class="panel"><h2>Server setup and device enrollment</h2><p>Run WireGuard on separate VPN servers. Use server tunnel address <code>10.66.0.1/16</code>, enable forwarding and outbound NAT, and install every device peer on every listed server. Keep server private keys on those servers. Mark a device ready only after provisioning all servers. Test connectivity before enabling VPN for everyone.</p><p>VPN server infrastructure and Firebase credentials are not created by this panel.</p><div class="table-wrap"><table><tr><th>Device</th><th>WireGuard peer configuration</th><th>Provisioning</th></tr>@forelse($peers as $p)<tr><td>{{ $p->label ?: $p->installation_id }}<br>{{ $p->vpn_status }}</td><td><pre>[Peer]
PublicKey = {{ $p->public_key }}
AllowedIPs = 10.66.{{ intdiv($p->id+1,256) }}.{{ ($p->id+1)%256 }}/32</pre></td><td><form method="post" action="{{ route('admin.vpn.peer',$p->id) }}">@csrf<select name="provisioned"><option value="0">Not ready</option><option value="1" @selected($p->provisioned)>Installed on all servers</option></select><button class="secondary">Save</button></form></td></tr>@empty<tr><td colspan="3">Devices enroll their public keys after upgrading. Private device keys never leave the phone.</td></tr>@endforelse</table>{{ $peers->links() }}</div></div>
<script>let vpnIndex={{ max(1,count($configuration['vpn']['servers'])) }};function addVpnServer(){if(vpnIndex>=3)return;let n=vpnIndex++;let row=document.createElement('div');row.className='fields';for(const [key,title] of [['name','Name'],['endpoint','Endpoint host:port'],['public_key','Server public key']]){let label=document.createElement('label'),input=document.createElement('input');label.textContent=title;input.name='servers['+n+']['+key+']';label.append(input);row.append(label)}document.getElementById('vpn-extra').append(row)}</script>
@endsection
